# Generated by Django 5.1.3 on 2024-12-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_project_date_project_file_project_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner_name',
        ),
    ]
