# Generated by Django 5.0.6 on 2025-05-02 19:47

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact_alter_clientpreview_template_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier, auto-filled from name.', max_length=60, null=True, unique=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (up to ~160 chars).', max_length=160, verbose_name='Meta description')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Last name')),
                ('phone', models.CharField(max_length=20, verbose_name='Mobile phone')),
                ('email', models.EmailField(max_length=254)),
                ('how_hear', models.CharField(choices=[('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('website', 'website'), ('other', 'Other')], max_length=20, verbose_name='How did you hear about us?')),
                ('cv', models.FileField(upload_to=home.models.cv_upload_to)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='home.jobcategory')),
            ],
        ),
    ]
