# Generated by Django 5.0.6 on 2025-05-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_jobcategory_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (up to ~160 chars).', max_length=160, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Keywords'),
        ),
    ]
