# Generated by Django on YYYY-MM-DD HH:MM
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_jobcategory_meta_keywords_project_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=60, unique=False, null=True, blank=True),
        ),
    ]