# Generated by Django X.X on 2025-05-05 15:38
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_project_slug'),  
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(
                allow_unicode=True,
                max_length=60,
                unique=False,    # no uniqueness yet
                null=True,
                blank=True,
                help_text="URL-friendly identifier, auto-filled later"
            ),
        ),
    ]